### ISSUE TITLE
use 6.4 and assetmapper

### ISSUE THREAD

**Issue by tacman** [Wordlesschunk/symfony6.4-pwa-boilerplate#1]
Although the title references 6.4, composer.json is locked at 6.3.*.

If you use 6.4, assetmapper is much better, a game changer.

A demo of using this to create a simply Symfony 6.4 app that's installable as a pwa would be really cool.  Thanks.

**Comment by Wordlesschunk** [comment]
Hey @tacman appreciate the feedback! This was just a basic repo as a base for future projects of mine, planning to make this into quite the 'one stop shop' for anything Symfony-PWA related. I've made the changes you've mentioned and my life has already been changed with this assetMapper, no longer the days of pain and suffering with webpack!

Thanks again!

**Comment by tacman** [comment]
Yes, AssetMapper rocks.  Do you have any demo repos that use this?  I'm still getting my head around PWA's, and would love to see a working one with Symfony, something easy and trivial.

In particular, stimulus makes it easy to swap out sections of the page and continue to use Symfony Routing, validation, etc, so you don't have to build a SPA first.  Forms are particularly hard to re-create in javascript, so I'm envisioning a PWA that fetches data from API platform and caches it for reading, and for adding data it attempts to push the form results out a POST endpoint but if it fails it caches the form data until the app is back online.

Most PWAs don't really leverage much of Symfony, but I think there's some very interesting possibilities, especially for sites that are largely read-only.
